config/routes.rb
Rails.application.routes.draw do
   resources :users
   resources :sessions
   resources :attractions
   resources :rides, only: [:new]
   root :to => 'welcome#greet'
   get '/signin' => 'sessions#new'
   get "/signout", to: "sessions#clear"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_many :rides
  has_many :users, through: :rides

  # def users_count
  #   users.length
  # end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :attraction

  def take_ride
    if self.attraction.tickets > self.user.tickets
      if user.height < attraction.min_height
        return "Sorry. You do not have enough tickets to ride the #{attraction.name}. You are not tall enough to ride the #{attraction.name}."
      end
      return "Sorry. You do not have enough tickets to ride the #{attraction.name}."
    end
    if user.height < attraction.min_height
      return "Sorry. You are not tall enough to ride the #{attraction.name}."
    end

    user.tickets-=attraction.tickets
    user.nausea+=attraction.nausea_rating
    user.happiness+=attraction.happiness_rating
    user.save
    return "Thanks for riding the #{self.attraction.name}!"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :rides
  has_many :attractions,through: :rides

  def mood
    if !happiness.nil? && !nausea.nil?
      if happiness > nausea
        "happy"
      elsif happiness < nausea
        "sad"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user

   if !session[:user_id].nil?
     @user=User.find(session[:user_id])
   else
     nil
   end
 end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  def index
    @attractions=Attraction.all
  end

  def new
    @attraction=Attraction.new
  end

  def show
    @attraction=Attraction.find(params[:id])
    @ride=Ride.create(attraction_id:@attraction.id,user_id:current_user.id)
  end

  def edit
    @attraction=Attraction.find(params[:id])
  end

  def update
    @attraction=Attraction.find(params[:id])
    @attraction.update(attractions_params)
    redirect_to attraction_path(@attraction)
  end

  def create
    @attraction=Attraction.create(attractions_params)
    if @attraction
      redirect_to attraction_path(@attraction)
    else
      redirect_to attractions_path
    end
  end

  def attractions_params
    params.require(:attraction).permit(:name,:tickets,:nausea_rating,:happiness_rating,:min_height)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
  end

  def create
    @ride=Ride.find(params[:id])

    puts @ride.take_ride

    redirect_to user_path(@ride.user)
  end

  def show
    @ride=Ride.find(params[:id])
  end

  def update
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(:name => params[:user][:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    if current_user
      session.delete :user_id
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def signin
  end

  def create

    @user=User.find(params[:user][:name])

    if @user && @user.authenticate(params[:password])
      session[:user_id]=@user.id
      redirect_to user_path @user
    else
      redirect_to "/"
    end
  end

  def destroy
    if !session[:user_id].nil?
      session.delete :user_id
      redirect_to "/"
    end
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_login
  # skip_before_action :require_login,only:[:create]
  def index
  end

  def new
    @user=User.new
  end


  def update
    @user=User.find(params[:id])
    flash[:message]=@user.rides.last.take_ride
    redirect_to user_path(@user)
  end

  def show
    if session[:user_id].nil?
      redirect_to "/"
    end
    @user=User.find(params[:id])
  end

  def create
    @user=User.create(users_params)
    if @user.valid?
      session[:user_id]=@user.id
      redirect_to user_path(@user)
    else
      redirect_to users_path
    end
  end

  def users_params
     params.require(:user).permit(:name,:happiness,:tickets,:nausea,:password,:height, :admin)
  end

end

app/controllers/welcome_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def log_out_link
    if logged_in?
      <<-HTML
        <a class="navbar-brand" href="<%= logout_url %>"/>Log Out</a>
      HTML
    else
      <<-HTML
      HTML
    end
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    session[:user_id]
end

app/helpers/users_helper.rb
module UsersHelper

  def admin?
    current_user.admin
  end
end

app/views/application/home.html.erb
<img src="https://i.imgur.com/sJHMUCz.jpg">
<h1>Welcome to the //Amusement Park!</h1>

app/views/attractions/_admin.html.erb
<ul>
<% attractions.each do |attraction| %>
  <li><%= link_to "Show #{attraction.name}", attraction_path(attraction) %></li>
<% end %>
</ul>
<%= link_to "New Attraction", new_attraction_path %>

app/views/attractions/_form.htlm.erb
<%= form_for(@attraction) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %><br><br>

    <%= f.label :min_height, "Height Requirement (in inches)" %><br>
    <%= f.number_field :min_height, class: "form-control" %><br><br>

    <%= f.label :happiness_rating, "How fun is it? (1-5 scale)" %><br>
    <%= f.number_field :happiness_rating, class: "form-control" %><br><br>

    <%= f.label :nausea_rating, "How nausea-inducing is it? (1-5 scale)" %><br>
    <%= f.number_field :nausea_rating, class: "form-control" %><br><br>

    <%= f.label :tickets, "How many tickets does it cost?" %><br>
    <%= f.number_field :tickets, class: "form-control" %><br><br>

    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
  <% if attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :min_height %>
    <%= form.text_field :min_height %>
  </div>

  <div class="field">
    <%= form.label :happiness_rating %>
    <%= form.text_field :happiness_rating %>
  </div>

  <div class="field">
    <%= form.label :nausea_rating %>
    <%= form.text_field :nausea_rating %>
  </div>

  <div class="field">
    <%= form.label :tickets %>
    <%= form.text_field :tickets %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Edit attraction Form</h1>

<%= render 'form' %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>
<table class="table">
  <tbody>
    <tr>
      <td ><strong>Name</strong></td>
      <td ><strong>Tickets</strong></td>
      <td><strong>Details</strong></td>
    </tr>

    <% @attractions.each do |attraction|%>
    <tr>
      <td><%= attraction.name %></td>
      <td><%= attraction.tickets %></td>
      <td>
        <%= link_to "Show #{attraction.name}", attraction_path(attraction) if @current_user.admin%>
        <%= link_to "Go on #{attraction.name}", attraction_path(attraction) unless @current_user.admin %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Back to profile", user_path(@current_user), {:class => "btn btn-primary"} %></p>
<p><%= link_to "New Attraction", new_attraction_path if @current_user.admin%></p>

app/views/attractions/new.html.erb
<h1>New attraction Form</h1>

<%= render 'form' %>

app/views/attractions/show.html.erb
<div class='center'>
  <div class='info' >
    <p><strong>Name:</strong> <%= @attraction.name %></p>
    <p><strong>Total Number of Users:</strong> <%= @attraction.users_count %></p>
    <p><strong>Nbr Ticket Requirement:</strong><%= @attraction.tickets %></p>
    <p><strong>Height Requirement:</strong> <%= @attraction.min_height %>inches</p>
    <p><strong>Nausea Rating:</strong><%= @attraction.nausea_rating %></p>
    <p><strong>Happiness Rating:</strong><%= @attraction.happiness_rating %></p>
    <% if @current_user.admin %>
      <p><%= link_to 'Edit Attraction', edit_attraction_path(@attraction)  %></p>
    <% else %>
      <%= form_for :ride, url: '/rides/new' do |f| %>
        <%= f.hidden_field :user_id, value: "#{@current_user.id}" %>
        <%= f.hidden_field :attraction_id, value: "#{@attraction.id}" %>
        <%= f.submit 'Go on this ride', class: 'btn btn-light' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/attractions/test.html.erb
<h1> Test here </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAmusementPark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% unless is_loging? %>
          <a class="navbar-brand" href="<%= signin_path %>"/>Log in</a>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
        <% else %>
          <%= link_to "Attractions", attractions_path, class: "navbar-brand" %>
          <%= link_to "#{@current_user.name}'s profile'", user_path(@current_user),  class: "navbar-brand" %>
          <%= link_to "Log Out", logout_session_path, method: :delete, class: "navbar-brand" %>
        <% end %>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rides/_form.html.erb
<%= form_with(model: ride, local: true) do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rides</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

app/views/session/new.html.erb
<h1>Sign In</h1>
<%= form_tag("/signin", method: "post") do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <p>Select a User:</p>
  <%= collection_select(:user, :name, User.all, :name, :name) %><br />
  <p>Password: <%= password_field_tag :password %></p>
  <%= submit_tag "Sign In" %>
<% end %>

app/views/static_pages/home.html.erb
<div>
  <div style='width: 600px;margin:auto'>
    <img  style='width: 600px'
<img src="https://i.imgur.com/sJHMUCz.jpg">
  </div>
  <h1 align="center">Welcome to the //Amusement Park!</h1>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :happiness %>
    <%= form.text_field :happiness %>
  </div>

  <div class="field">
    <%= form.label :nausea %>
    <%= form.text_field :nausea %>
  </div>

  <div class="field">
    <%= form.label :tickets %>
    <%= form.text_field :tickets %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.text_field :admin, id:"user_admin" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= render 'form' %>

app/views/users/home.html.erb
<h1>Welcome to Rails Amusement Park, <%= current_user.name %></h1>.

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>

  <%= f.label :height %><br>
  <%= f.text_field :height %><br><br>

  <%= f.label :happiness %><br>
  <%= f.text_field :happiness %><br><br>

  <%= f.label :nausea %><br>
  <%= f.text_field :nausea %><br><br>

  <%= f.label :tickets %><br>
  <%= f.text_field :tickets %><br><br>

  <%= f.label :admin, "Check box if you are a park owner" %>
  <%= f.check_box :admin %><br><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<% if flash[:message] %>
  <div class="center alert">
    <p><%= flash[:message] %></p>
  </div>
<% end %>
<div class="center">
  <div class="info">
    <% if @user.admin%>
      <p>ADMIN</p>
    <% end %>
    <p><strong>Name:</strong> <%= @user.name %></p>

    <p><strong>Mood:</strong> <%= @user.mood %></p>
    <p><strong>Height:</strong> <%= @user.height %></p>
    <p><strong>Tickets:</strong> <%= @user.tickets %></p>

    <%= link_to "See attractions", attractions_path %>
  </div>
</div>

app/views/welcome/greet.html.erb
<!DOCTYPE html>
<html>
<body>
<img style="width: 600px"
     src="https://images5.alphacoders.com/400/400078.jpg">

     <h1 align="center">Welcome to the Rails Amusement Park!</h1>

     <center>
       <h1><%= link_to "Log In", new_session_path %></h1>
       <h1><%= link_to "Sign Up", new_user_path %></h1>
     </center>
   </body>
  </html>

app/views/welcome/home.html.erb
<h1>Welcome to the //Amusement Park!</h1>
<h2><%= link_to	'Sign Up', '/users/new' %></h2>

app/views/welcome/index.html.erb
<div style="width:600px;margin:auto">
  <img style="width: 600px" src="http://www.washingtonpost.com/wp-srv/special/health/why-roller-coasters-make-us-scream/images/rollercoasterBackground.jpg">
<h1 align="center">Welcome to the //Amusement Park!</h1>
</div>